name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install boto3 psycopg2-binary python-decouple python-dotenv pyinstaller

      - name: Create configs
        run: |
          mkdir configs
          echo "${{ secrets.ENV_FILE }}" > configs/.env
          echo "${{ secrets.PRODUCTION_ENV_FILE }}" > configs/production.env

      - name: Build EXE
        run: |
          pyinstaller --onefile --add-data "configs;configs" uploader.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploader-windows
          path: dist\uploader.exe
